services:
  elttl_react_mysql:
    container_name: elttl_react_mysql
    image: mysql:8.0
    restart: on-failure
    ports:
      - 33062:3306
    volumes:
      - elttl_react_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
volumes:
  elttl_react_mysql_data: